version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://platform:platform123@postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: 'ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: 'Europe/London'
    _AIRFLOW_WWW_USER_USERNAME: admin
    _AIRFLOW_WWW_USER_PASSWORD: admin123
    SPARK_MASTER: spark://spark-master:7077
    SCHEMA_REGISTRY_URL: http://schema-registry:8000
    MINIO_ENDPOINT: http://minio:9000
    MINIO_ACCESS_KEY: admin
    MINIO_SECRET_KEY: changeme123456
    KAFKA_BOOTSTRAP: kafka:29092
  volumes:
    - ../../pipelines/dags:/opt/airflow/dags
    - ../../pipelines/spark:/opt/airflow/spark_jobs
    - airflow-logs:/opt/airflow/logs
    - /var/run/docker.sock:/var/run/docker.sock
  user: "0:0"
  depends_on:
    postgres:
      condition: service_healthy
  networks:
    - platform-network

services:

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@platform.local \
          --password admin123 || true
        echo "Airflow initialised successfully"
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    hostname: airflow-webserver
    ports:
      - "8888:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    hostname: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  airflow-logs:
    driver: local

networks:
  platform-network:
    external: true
    name: platform-network
